model_name: QwenImageEdit-2509

vae_type: AutoencoderKLQwenImage
pipeline_type: QwenImageEditPipeline
noise_scheduler_type: FlowMatchEulerDiscreteScheduler

vae:
  type: diffusers.${vae_type}.from_pretrained
  params:
    pretrained_model_name_or_path: ${model_name}
    subfolder: vae


pipeline:
  type: diffusers.${pipeline_type}.from_pretrained
  params:
    pretrained_model_name_or_path: ${model_name}

noise_scheduler:
  type: diffusers.${noise_scheduler_type}.from_pretrained
  params:
    pretrained_model_name_or_path: ${model_name}
    subfolder: scheduler

normalize_latents:
  type: torchvision.transforms.Normalize
  args:
    mean:
      object:
        object: ${vae}
        config:
      latents_mean:
    std:
      object:
        object: ${vae}
        config:
      latents_std: