model_name: QwenImageEdit-2509

vae_type: AutoencoderKLQwenImage
pipeline_type: QwenImageEditPipeline
noise_scheduler_type: FlowMatchEulerDiscreteScheduler

vae:
  type: diffusers.${vae_type}.from_pretrained
  params:
    pretrained_model_name_or_path: ${model_name}
    subfolder: vae

vae_scale_factor:
  type: operator.pow
  args:
    - 2
    - type: builtins.len
      args:
        object: ${vae}
        temperal_downsample:

pipeline:
  type: diffusers.${pipeline_type}.from_pretrained
  params:
    pretrained_model_name_or_path: ${model_name}

noise_scheduler:
  type: diffusers.${noise_scheduler_type}.from_pretrained
  params:
    pretrained_model_name_or_path: ${model_name}
    subfolder: scheduler

timesteps:
    object: ${noise_scheduler}
    timesteps:

sigmas:
    object: ${noise_scheduler}
    sigmas:

normalize_latents:
  type: torchvision.transforms.Normalize
  args:
    mean:
      object:
        object: ${vae}
        config:
      latents_mean:
    std:
      object:
        object: ${vae}
        config:
      latents_std: